#
# To run this Makefile, the environment variable "PLOVR" must be set to the
# plovr jar file
#
# The global Makefile in the project root takes care of this.
#

all:
	java -jar ${PLOVR} build plovr-config.js
